### ISSUE TITLE
LDAP and automatic account creation?

### ISSUE THREAD

**Issue by matlag** [YunoHost-Apps/hubzilla_ynh#12]
Hi there!
Is there a plan to have an automatic post-install configuration to create accounts for each Yunohost users and use Yunohost's LDAP?
Thanks!

**Comment by anaqreon** [comment]
We do not have plans to do this. While it may be possible to do what you describe, Hubzilla accounts are rather complicated and it's probably not worth the effort given how easy it is to register via Hubzilla itself. We do not have enough developers knowledgeable enough in both YunoHost and Hubzilla working on this package yet. That being said, it's all open source, so if someone figures out how to integrate YunoHost SSO system with the Hubzilla instance, I'm sure it would be a welcome addition to the package.

**Comment by anmol26s** [comment]
The Hubzilla app now has Ldap support. You can test it and close the issue.

**Comment by anmol26s** [comment]
This issue has been resolved long time back. I am closing it for now. Re-open it, if someone have any problem in logging through LDAP.
