### ISSUE TITLE
Pubstream not working on 8.0

### ISSUE THREAD

**Issue by xarnes** [YunoHost-Apps/hubzilla_ynh#134]
The pubstream does not show entries on both an updated instance(on VPS) and a freshly installed one(on VirtualBox).
For comparison, I deployed Hubzilla 8.0 without YunoHost and everything works there.
I enabled the pubstream in the site settings and added an entry then went to the address /pubstream

If you restore the previous version from backup, the pubstream works again

YunoHost 11.0.11
Hubzilla 8.0

**Comment by cdedert** [comment]
I'm having a similar issue. Updated to 8.0. Now, 1 of 5 channels won't load the public stream or the personal stream. All other channels seem to work fine. I tried to uninstall/reinstall the public stream app. I tried to uninstall/reinstall the ActivityPub app.
