### ISSUE TITLE
Update to version 8.8.7 apparently urgently required

### ISSUE THREAD

**Issue by PericlesSyC** [YunoHost-Apps/hubzilla_ynh#165]
[Mario Vavti urgently recommends](https://hub.somaton.com/channel/mario?mid=b64.aHR0cHM6Ly9odWIuc29tYXRvbi5jb20vaXRlbS85MDcyOTk2MC1mMzhkLTQ2ZjUtYTA1MC1mNmVkOGMwZDIxOWY) updating to the new version as soon as possible:

> Hubzilla 8.8.7
> - Fix regression in Activity::actor_store()
>
> If you are on version 8.8.x or 8.9.x please update ASAP!

**Comment by rocky-III** [comment]
> [Mario Vavti urgently recommends](https://hub.somaton.com/channel/mario?mid=b64.aHR0cHM6Ly9odWIuc29tYXRvbi5jb20vaXRlbS85MDcyOTk2MC1mMzhkLTQ2ZjUtYTA1MC1mNmVkOGMwZDIxOWY) updating to the new version as soon as possible:

@ericgaspar

**Comment by PericlesSyC** [comment]
In the meantime, there is already another update:

Version 8.8.8

https://hub.somaton.com/channel/mario?mid=af59a56d-bf74-497d-8bf9-f9e736739306

**Comment by rocky-III** [comment]
The Hubzilla Yunohost packet is not up to date since more than 2 month now !

Meanwhile we got Hubzilla 9.0 released! 
https://hub.somaton.com/channel/mario?mid=4214a375-3a18-4acb-b546-75c6c4818e2f

What has to be done so that the Hubzilla Yunohost packet gets updated as well?  Thanks

**Comment by PericlesSyC** [comment]
[Hubzilla 9.0.1 Released!](https://hub.somaton.com/item/74d4c836-dbfe-4679-b4ec-5b6fa5273e59?f=&zid=pepecyb%40hub.hubzilla.hu)

**ATTENTION:** This release contains important security fixes. **Please update ASAP!**
