### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/hubzilla_ynh#24]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/hubzilla%20(Community)/43/console

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by anmol26s** [comment]
The CI shows php-xml package not found. But on my system it was not installed and I have to install it manually.
Do you want that I remove it ?

**Comment by maniackcrudelis** [comment]
Well, if you have to install the package manually, I guess that I mean that this package have to be installed.
But, I'm not sure to understand what do you mean by "I have to install it manually", since it's already a dependency of this app.

**Comment by maniackcrudelis** [comment]
php-xml is only available on stretch

**Comment by anmol26s** [comment]
I was on Jessie with php7 that maybe issue that I needed to install on the this package manually. I have added this package after I faced the issue with the app running on php7. 
The CI says that  ` Warning: yunohost.hook <lambda> - [1047.1] E: Unable to locate package php-xml`, but for YunoHost 3 with php7 this package is required.

**Comment by maniackcrudelis** [comment]
Ok, so you find a package php-xml on jessie then ?
Anyway, on a conventional YunoHost jessie, php-xml isn't available, so you will have to use the same trick than kanboard to add this dependency only for stretch

**Comment by anmol26s** [comment]
I have the package. I am on stretch but not yet migrated to YunoHost 3 beta.
But what if in future person upgrade to stretch(yunohost 3) from jessie, then how will the package be added to the dependency through the upgrade script?

**Comment by maniackcrudelis** [comment]
I'm not sure that I understood you.

Anyway, to answer your question, we currently don't have any real "good" solution in case of migration from Jessie to Stretch, relating to missing packages. The only solution is currently to run an upgrade of the app after the migration, so the upgrade script will install the missing dependencies, since the system will be, then, on Stretch.

**Comment by anmol26s** [comment]
Can you tell me why the installation fails now?
https://ci-apps.yunohost.org/jenkins/job/hubzilla%20(Community)/lastBuild/console

**Comment by maniackcrudelis** [comment]
You missed double quotes around the dependencies line 69

**Comment by anmol26s** [comment]
Thanks
How can I manually run Cl for the app.

**Comment by maniackcrudelis** [comment]
You can either install [Package check](https://github.com/YunoHost/package_check) on a virtual machine, a VPS or anything else running on debian.
Or using the [dev CI](https://ci-apps-dev.yunohost.org/jenkins/) which need only a public ssh key and a login to create an account for you.

**Comment by anmol26s** [comment]
Closing this as CI is happy now.
 https://ci-apps.yunohost.org/jenkins/job/hubzilla%20(Community)/51/console
