### ISSUE TITLE
The installation is missing the mbstring php extension. 

### ISSUE THREAD

**Issue by tofeo** [YunoHost-Apps/hubzilla_ynh#25]
I tryed to install hubzilla on debian9.5 and I got a white page

#0 /var/www/hubzilla/include/channel.php(105): create_identity(Array)
#1 /var/www/hubzilla/boot.php(1418): create_sys_channel()
#2 /var/www/hubzilla/Zotlabs/Web/WebServer.php(106): check_config()
#3 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run()
#4 {main}
thrown in /var/www/hubzilla/include/channel.php on line 198" while reading response header from upstream, client: 178.238.172.190, server: hub.actocom.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "hub.actocom.com"
2018/08/18 23:29:52 [error] 32495#32495: *7996 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function mb_strtolower() in /var/www/hubzilla/include/channel.php:198
Stack trace:
apparently mbstring php extension was missing

**Comment by anmol26s** [comment]
Thanks for the opening the issue and sorry for the late reply.
Is the issue resolved by installing the **php-mbstring** extension?

**Comment by anmol26s** [comment]
Fixed: https://github.com/YunoHost-Apps/hubzilla_ynh/commit/c736d61ae01a677353448003f7313df5f7bbfa20
