### ISSUE TITLE
 updated to 4.21

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/hubzilla_ynh#27]
Hi
I wonder if hubzilla_ynh will be updated to 4.21 ?
Is there a reason why the update could not work with yunoHost?
thanks

**Comment by anmol26s** [comment]
I will work on this.

**Comment by AkselRocks** [comment]
I am also interested in hubzilla_ynh update. Is there a progress?

**Comment by rocky-III** [comment]
what can we do? anmol can you teach us ?

**Comment by AkselRocks** [comment]
hubzilla 4.21 and the latest version 4.4 needs php >7.1.
debian 9 and yunohost uses php 7.0 as default.

I guess one is waiting für next main version of yunohost with debian 10 (buster), which uses php7.3 as default.

**Comment by rocky-III** [comment]
Ahh.... thanks for the Info Aksel

**Comment by anmol26s** [comment]
Updated to latest version 4.7.2. So closing this.

**Comment by rocky-III** [comment]
anmaol26 thanks so much
