### ISSUE TITLE
error cron logrotate

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/hubzilla_ynh#39]
After a new installation of Hubzilla I get an error mail:
```
/etc/cron.daily/logrotate:
error: skipping "/var/www/hubzilla/php.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
run-parts: /etc/cron.daily/logrotate exited with return code 1
```
the directory is `4 drwxr-xr-x 17 hubzilla       hubzilla 4096 Jun 21 07:27 hubzilla`

I guess it should be hubzilla:root. (?)

**Comment by anmol26s** [comment]
Helloo,

Hmm, but did the logrotate ran on the php.log? Root should not have problem to access it.
