### ISSUE TITLE
Deinstallation won't delete /home/hubzilla

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/hubzilla_ynh#40]
After deinstallation of hubzilla there is still a user folder /home/hubzilla left.

**Comment by anmol26s** [comment]
Helloo,

Please provide the logs. There may be some interruption in the script while app was being removed.

**Comment by anmol26s** [comment]
This cannot happen because this app never created /home/hubzilla. The user for the app is also created without home directory.
