### ISSUE TITLE
Lost installation after update

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/hubzilla_ynh#44]
just did the last update and lost my installation... the URL of my hub now links me just to the yunohost panel and HZ is not showed anymore in this panel 
https://paste.yunohost.org/raw/tihexacefa

Heeeeellp Thanks

**Comment by rocky-III** [comment]
Dont see HZ anymore under https://my.domain.de/yunohost/admin/#/apps

Ohhh no...

**Comment by rocky-III** [comment]
on an second server where I did the update , I just get now "502 Bad Gateway"

**Comment by anmol26s** [comment]
Are you on the latest version of Yunohost?
`$yunhost -v`


That is strange error. I thought we had force remove in ynh_secure_remove. Its giving error for this.
`rm: cannot remove '/var/www/hubzilla': Directory not empty`

Can you try to restore the app again? You got two error one while upgrade and one while restore. Mysql looks messed up too.
Show logs of these.
```
$ service mysql status
$ journalctl -u mariadb.service 
```

Show the Nginx logs of the second server.
`$ tail -n 100 /var/log/nginx/your-domain.com-error.log`

**Comment by rocky-III** [comment]
Thanks vor your help

```
# service mysql status                                                                                                          
● mariadb.service - MariaDB 10.1.47 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)                                                 
   Active: active (running) since Tue 2020-11-03 12:57:59 UTC; 2h 52min ago
     Docs: man:mysqld(8)                                                                                                                 
           https://mariadb.com/kb/en/library/systemd/                                                                                    
  Process: 1683 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)               
  Process: 1649 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)                                                    
  Process: 1145 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`cd /usr/bin/..; /usr/bin/galera_recovery`; [ 
  Process: 1047 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)                
  Process: 974 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)                  
 Main PID: 1327 (mysqld)                                                                                                                 
   Status: "Taking your SQL requests now..."                                                                                             
    Tasks: 26 (limit: 4915)                                                                                                              
   CGroup: /system.slice/mariadb.service                                                                                                 
           └─1327 /usr/sbin/mysqld                                                                                                       
                                                                                                                                         
Nov 03 12:57:54 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:54 3069258544 [Note] InnoDB: Highest supported file format is Barracuda.    
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: 128 rollback segment(s) are active.            
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: Waiting for purge to start                     
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.49
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Plugin 'FEEDBACK' is disabled.                         
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 2499801920 [Note] InnoDB: Dumping buffer pool(s) not yet started         
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Server socket created on IP: '::'.                     
Nov 03 12:57:58 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:58 3069258544 [Note] /usr/sbin/mysqld: ready for connections.               
Nov 03 12:57:58 my.infozoo.de mysqld[1327]: Version: '10.1.47-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Debia
Nov 03 12:57:59 my.infozoo.de systemd[1]: Started MariaDB 10.1.47 database server.                                                       
...skipping...
● mariadb.service - MariaDB 10.1.47 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)                                                 
   Active: active (running) since Tue 2020-11-03 12:57:59 UTC; 2h 52min ago
     Docs: man:mysqld(8)                                                                                                                 
           https://mariadb.com/kb/en/library/systemd/                                                                                    
  Process: 1683 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)               
  Process: 1649 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)                                                    
  Process: 1145 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`cd /usr/bin/..; /usr/bin/galera_recovery`; [ 
  Process: 1047 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)                
  Process: 974 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)                  
 Main PID: 1327 (mysqld)                                                                                                                 
   Status: "Taking your SQL requests now..."                                                                                             
    Tasks: 26 (limit: 4915)                                                                                                              
   CGroup: /system.slice/mariadb.service                                                                                                 
           └─1327 /usr/sbin/mysqld                                                                                                       
                                                                                                                                         
Nov 03 12:57:54 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:54 3069258544 [Note] InnoDB: Highest supported file format is Barracuda.    
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: 128 rollback segment(s) are active.            
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: Waiting for purge to start                     
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.49
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Plugin 'FEEDBACK' is disabled.                         
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 2499801920 [Note] InnoDB: Dumping buffer pool(s) not yet started         
Nov 03 12:57:57 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Server socket created on IP: '::'.                     
Nov 03 12:57:58 my.infozoo.de mysqld[1327]: 2020-11-03 12:57:58 3069258544 [Note] /usr/sbin/mysqld: ready for connections.               
Nov 03 12:57:58 my.infozoo.de mysqld[1327]: Version: '10.1.47-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Debia
Nov 03 12:57:59 my.infozoo.de systemd[1]: Started MariaDB 10.1.47 database server. 
```

**Comment by rocky-III** [comment]
```
journalctl -u mariadb.service                                                                                                 
-- Logs begin at Tue 2020-11-03 12:57:24 UTC, end at Tue 2020-11-03 15:52:48 UTC. --                                                     
Nov 03 12:57:44 my.domain.de systemd[1]: Starting MariaDB 10.1.47 database server...                                                    
Nov 03 12:57:51 my.domain.de mysqld[1327]: 2020-11-03 12:57:51 3069258544 [Warning] option 'table_open_cache': unsigned value 4 adjusted
Nov 03 12:57:51 my.domain.de mysqld[1327]: 2020-11-03 12:57:51 3069258544 [Note] /usr/sbin/mysqld (mysqld 10.1.47-MariaDB-0+deb9u1) star
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: innodb_empty_free_list_algorithm has been chang
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Using mutexes to ref count buffer pool pages   
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: The InnoDB memory heap is disabled             
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins   
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Compressed tables use zlib 1.2.8               
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Using Linux native AIO                         
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Using generic crc32 instructions               
Nov 03 12:57:52 my.domain.de mysqld[1327]: 2020-11-03 12:57:52 3069258544 [Note] InnoDB: Initializing buffer pool, size = 128.0M        
Nov 03 12:57:53 my.domain.de mysqld[1327]: 2020-11-03 12:57:53 3069258544 [Note] InnoDB: Completed initialization of buffer pool        
Nov 03 12:57:54 my.domain.de mysqld[1327]: 2020-11-03 12:57:54 3069258544 [Note] InnoDB: Highest supported file format is Barracuda.    
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: 128 rollback segment(s) are active.            
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB: Waiting for purge to start                     
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.49
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Plugin 'FEEDBACK' is disabled.                         
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 2499801920 [Note] InnoDB: Dumping buffer pool(s) not yet started         
Nov 03 12:57:57 my.domain.de mysqld[1327]: 2020-11-03 12:57:57 3069258544 [Note] Server socket created on IP: '::'.                     
Nov 03 12:57:58 my.domain.de mysqld[1327]: 2020-11-03 12:57:58 3069258544 [Note] /usr/sbin/mysqld: ready for connections.               
Nov 03 12:57:58 my.domain.de mysqld[1327]: Version: '10.1.47-MariaDB-0+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Debia
Nov 03 12:57:59 my.domain.de systemd[1]: Started MariaDB 10.1.47 database server.                                                       
lines 1-24/24 (END)
```

**Comment by rocky-III** [comment]
> Show the Nginx logs of the second server.
> $ tail -n 100 /var/log/nginx/your-domain.com-error.log

https://paste.yunohost.org/raw/urixojafuw

**Comment by rocky-III** [comment]
> Can you try to restore the app again? 
How could I try this?

**Comment by anmol26s** [comment]
Its an error of InnoDb which is a database storage engine. I have not gone deep into it. But it might be reason for mysql crash.

You can try to restore Hubzilla.
`$ yunohost backup restore --app hubzilla hubzilla-pre-upgrade1 --debug `
Note: The upgrade can be upgrade1 or upgrade2. So if upgrade1 do not work try it with upgrade2. Or just do:
`$ ls -l /home/yunohost.backup/archives`
and see what is the name of the Hubzilla backup.

**Comment by rocky-III** [comment]
what I´m doing wrong?
```
root@my:~# $ ls -l /home/yunohost.backup/archives                                                                      
$: command not found                                                                                                   
root@my:~# yunohost backup restore --app hubzilla hubzilla-pre-upgrade1 --debug                                        
898  DEBUG loading actions map namespace 'yunohost'
1081 DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
1083 DEBUG initializing base actions map parser for cli
1092 DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
usage: yunohost backup restore name [-h] [--system [SYSTEM [SYSTEM ...]]] [--apps [APPS [APPS ...]]] [--force]         
yunohost backup restore: error: too few arguments                                                                      
root@my:~# yunohost backup restore --app hubzilla hubzilla-pre-upgrade2 --debug                                        
790  DEBUG loading actions map namespace 'yunohost'
963  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
964  DEBUG initializing base actions map parser for cli
974  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
usage: yunohost backup restore name [-h] [--system [SYSTEM [SYSTEM ...]]] [--apps [APPS [APPS ...]]] [--force]         
yunohost backup restore: error: too few arguments                                                                      
                                                          
```

**Comment by rocky-III** [comment]
```
root@my:~#  ls -l /home/yunohost.backup/archives
-rw-r--r-- 1 root root 1727497459 Nov  1 02:39 hubzilla_backup.tar.gz                                                  
-rw-r--r-- 1 root root        324 Nov  3 10:35 hubzilla-pre-upgrade2.info.json                                         
-rw-r--r-- 1 root root 1729543983 Nov  3 10:35 hubzilla-pre-upgrade2.tar.gz   
```

so shell I try
`yunohost backup restore --app hubzilla hubzilla-pre-upgrade2.tar.gz   --debug `           ??

**Comment by anmol26s** [comment]
This should work:
`$ yunohost backup restore --app hubzilla hubzilla-pre-upgrade2`

**Comment by rocky-III** [comment]
```
root@my:~# yunohost backup restore --app hubzilla hubzilla-pre-upgrade                                                 
usage: yunohost backup restore name [-h] [--system [SYSTEM [SYSTEM ...]]] [--apps [APPS [APPS ...]]] [--force]         
yunohost backup restore: error: too few arguments                                                                      
root@my:~#  
```

**Comment by anmol26s** [comment]
(•‿•)

Try this:
`$ yunohost backup restore  hubzilla-pre-upgrade2 --debug`

**Comment by rocky-III** [comment]
```
root@my:~# root@my:~#yunohost backup restore --app hubzilla hubzilla-pre-upgrade2                                      
root@my:~#yunohost: command not found                                                                                  
root@my:~#  
```

**Comment by rocky-III** [comment]
```
root@my:~# yunohost backup restore hubzilla-pre-upgrade2 --debug                                                       
792  DEBUG loading actions map namespace 'yunohost'
964  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
966  DEBUG initializing base actions map parser for cli
975  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
1619 DEBUG acquiring lock...
1833 DEBUG lock has been acquired
2410 DEBUG loading python module yunohost.backup took 0.574s
2412 INFO processing action [14492.1]: yunohost.backup.restore with args={'force': False, 'apps': None, 'name': 'hubzil
la-pre-upgrade2', 'system': None}                                                                                      
2415 WARNING YunoHost is already installed
Do you really want to restore an already installed system? [y/N]: 
```
shell i go for it ?

**Comment by anmol26s** [comment]
Yes

**Comment by rocky-III** [comment]
did not work :-(
https://paste.yunohost.org/raw/konipehifi

**Comment by anmol26s** [comment]
Show output of:
`$ mariadb --version`
and
`$ cat /etc/mysql/my.cf`
then try doing:
```
$ sed -i 's/max_allowed_packet = 1M/max_allowed_packet = 64M/g' /etc/mysql/my.cnf
$ service mysql restart
$  yunohost backup restore hubzilla-pre-upgrade2 --debug    
```

**Comment by rocky-III** [comment]
```
root@my:~# mariadb --version
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2                                                    
root@my:~# cat /etc/mysql/my.cf                                                                                                                      
cat: /etc/mysql/my.cf: No such file or directory                                                                                                     
root@my:~#      
```

**Comment by rocky-III** [comment]
```
root@my:~# sed -i 's/max_allowed_packet = 1M/max_allowed_packet = 64M/g' /etc/mysql/my.cnf                                                           
root@my:~#    
```

**Comment by anmol26s** [comment]
> root@my:~# cat /etc/mysql/my.cf                                                                                                                      
> cat: /etc/mysql/my.cf: No such file or directory   
sorry it was 
root@my:~# cat /etc/mysql/my.cf

**Comment by rocky-III** [comment]
`root@my:~# cat /etc/mysql/my.cnf                                                                                 
# Example MySQL config file for small systems.                                                                   
#                                                                                                                
# This is for a system with little memory (<= 64M) where MySQL is only used                                      
# from time to time and it's important that the mysqld daemon                                                    
# doesn't use much resources.                                                                                    
#                                                                                                                
# MySQL programs look for option files in a set of                                                               
# locations which depend on the deployment platform.                                                             
# You can copy this option file to one of those                                                                  
# locations. For information about these locations, see:                                                         
# http://dev.mysql.com/doc/mysql/en/option-files.html                                                            
#                                                                                                                
# In this file, you can use all long options that a program supports.                                            
# If you want to know which options a program supports, run the program                                          
# with the "--help" option.                                                                                      
                                                                                                                 
# The following options will be passed to all MySQL clients                                                      
[client]                                                                                                         
#password       = your_password                                                                                  
port            = 3306                                                                                           
socket          = /var/run/mysqld/mysqld.sock                                                                    
                                                                                                                 
# Here follows entries for some specific programs                                                                
                                                                                                                 
# The MySQL server                                                                                               
[mysqld]                                                                                                         
port            = 3306                                                                                           
socket          = /var/run/mysqld/mysqld.sock                                                                    
skip-external-locking                                                                                            
key_buffer_size = 16K                                                                                            
max_allowed_packet = 64M                                                                                         
table_open_cache = 4                                                                                             
sort_buffer_size = 64K                                                                                           
read_buffer_size = 256K                                                                                          
read_rnd_buffer_size = 256K                                                                                      
net_buffer_length = 2K                                                                                           
thread_stack = 128K                                                                                              
                                                                                                                 
# to avoid corruption on powerfailure                                                                            
default-storage-engine=innodb                                                                                    
                                                                                                                 
# Don't listen on a TCP/IP port at all. This can be a security enhancement,                                      
# if all processes that need to connect to mysqld run on the same host.                                          
# All interaction with mysqld must be made via Unix sockets or named pipes.                                      
# Note that using this option without enabling named pipes on Windows                                            
# (using the "enable-named-pipe" option) will render mysqld useless!                                             
#                                                                                                                
#skip-networking                                                                                                 
server-id       = 1                                                                                              
                                                                                                                 
# Uncomment the following if you want to log updates                                                             
#log-bin=mysql-bin                                                                                               
                                                                                                                 
# binary logging format - mixed recommended                                                                      
#binlog_format=mixed                                                                                             
                                                                                                                 
# Causes updates to non-transactional engines using statement format to be                                       
# written directly to binary log. Before using this option make sure that                                        
# there are no dependencies between transactional and non-transactional                                          
# tables such as in the statement INSERT INTO t_myisam SELECT * FROM                                             
# t_innodb; otherwise, slaves may diverge from the master.                                                       
#binlog_direct_non_transactional_updates=TRUE                                                                    
                                                                                                                 
# Uncomment the following if you are using InnoDB tables                                                         
#innodb_data_home_dir = /var/lib/mysql                                                                           
#innodb_data_file_path = ibdata1:10M:autoextend                                                                  
#innodb_log_group_home_dir = /var/lib/mysql                                                                      
# You can set .._buffer_pool_size up to 50 - 80 %                                                                
# of RAM but beware of setting memory usage too high                                                             
#innodb_buffer_pool_size = 16M                                                                                   
#innodb_additional_mem_pool_size = 2M                                                                            
# Set .._log_file_size to 25 % of buffer pool size                                                               
#innodb_log_file_size = 5M                                                                                       
#innodb_log_buffer_size = 8M                                                                                     
#innodb_flush_log_at_trx_commit = 1                                                                              
#innodb_lock_wait_timeout = 50                                                                                   
                                                                                                                 
[mysqldump]                                                                                                      
quick                                                                                                            
max_allowed_packet = 16M                                                                                         
                                                                                                                 
[mysql]                                                                                                          
no-auto-rehash                                                                                                   
# Remove the next comment character if you are not familiar with SQL                                             
#safe-updates                                                                                                    
                                                                                                                 
[myisamchk]                                                                                                      
key_buffer_size = 8M                                                                                             
sort_buffer_size = 8M                                                                                            
                                                                                                                 
[mysqlhotcopy]                                                                                                   
interactive-timeout                                                                                              
root@my:~# sed -i 's/max_allowed_packet = 1M/max_allowed_packet = 64M/g' /etc/mysql/my.cnf                       
root@my:~#                                                                                                       `

**Comment by anmol26s** [comment]
You can restart mysql and try restoring again.

```
$ service mysql restart
$  yunohost backup restore hubzilla-pre-upgrade2 --debug 
```

**Comment by rocky-III** [comment]
It worked!!!
@anmol26s thanks so much - with your help the hub is alive again... UFFfffff... what would I do with out you !

**Comment by rocky-III** [comment]
@anmol26s  shell i try to restor the secound server the same way?

**Comment by anmol26s** [comment]
> Show the Nginx logs of the second server.
> $ tail -n 100 /var/log/nginx/your-domain.com-error.log

Can you show me Nginx logs?

**Comment by rocky-III** [comment]
> 
> 
>     Show the Nginx logs of the second server.
>     $ tail -n 100 /var/log/nginx/your-domain.com-error.log

https://paste.yunohost.org/raw/urixojafuw

**Comment by anmol26s** [comment]
Updating the app should fix this.
But before doing that. Go to:
`$ cd /home/yunohost.app/archives`
and take the backup of the hubzilla
`$ cp   hubzilla-pre-upgrade2 hubzilla04112020`

**Comment by rocky-III** [comment]
```
root@my:~# cd /home/yunohost.app/archives                                                                                        
-bash: cd: /home/yunohost.app/archives: No such file or directory                                                                         
root@my:~#    
```       
archives does not exist

**Comment by rocky-III** [comment]
in
/home/yunohost.backup/archives
I see the file 
hubzilla-pre-upgrade2.tar.gz

so i will back up this file - right? 
and than start the restor porsess - right?

**Comment by anmol26s** [comment]
Keep hubzilla-pre-upgrade2.tar.gz to a safe place as it is the working backup. Then try to upgrade again.
Then try to upgrade.

**Comment by rocky-III** [comment]
```
                                                                                              
root@my:~# yunohost backup restore hubzilla-pre-upgrade2 --debug                                                                 
287  DEBUG loading actions map namespace 'yunohost'
309  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
309  DEBUG initializing base actions map parser for cli
310  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
364  DEBUG acquiring lock...
441  DEBUG lock has been acquired
710  DEBUG loading python module yunohost.backup took 0.268s
710  INFO processing action [10443.1]: yunohost.backup.restore with args={'force': False, 'apps': None, 'name': 'hubzilla-pre-upgrade2', '
system': None}                                                                                                                            
711  WARNING YunoHost is already installed
Do you really want to restore an already installed system? [y/N]: y
5905 DEBUG action [10443.1] executed in 5.195s
5905 DEBUG lock has been released
5906 ERROR The following apps can't be restored because they are already installed: hubzilla
root@my:~#  
```

**Comment by rocky-III** [comment]
I I will try this
`sudo yunohost app upgrade hubzilla -u https://github.com/YunoHost-Apps/hubzilla_ynh --debug`
right?

**Comment by anmol26s** [comment]
Yes

**Comment by rocky-III** [comment]
did not work
https://paste.yunohost.org/raw/oceyalonew

shell i now try a restor

**Comment by anmol26s** [comment]
First check your Debian version:
`$ lsb_release --codename --short`
If its Stretch then update to buster.  
See this [doc](https://yunohost.org/#/stretch_buster_migration) for migration. If you have other imp apps, make a [backup](https://yunohost.org/#/backup) of them. The go ahead and migrate to buster.

**Comment by rocky-III** [comment]
still on buster

**Comment by rocky-III** [comment]
still on Stretch

**Comment by rocky-III** [comment]
still on Stretch

**Comment by rocky-III** [comment]
can´t migrate to buster because can´t update the system
https://paste.yunohost.org/raw/nojifereka

`Failed to start The PHP 7.0 FastCGI Process Manager.`

waht can i do?

**Comment by anmol26s** [comment]
Do this:
`$ mv /etc/php/7.0/fpm/pool.d/hubzilla.conf  /etc/php/7.0/fpm/pool.d/hubzilla.conf.backup `

Then try migration again.

**Comment by rocky-III** [comment]
thanks... 

now during the update the proses was stoped because of time out... (?)
and now lock in as root does not work any more   grrrrrr....r

```
admin-tools.lokal.social login: root                                                                                                      
                                                                                                                                          
Login incorrect                                                                                                                           
admin-tools.lokal.social login: root                                                                                                      
                                                                                                                                          
Login incorrect                                                                                                                           
admin-tools.lokal.social login:     
```

**Comment by anmol26s** [comment]
You should now come on [support chat](https://yunohost.org/#/help) from here or write/search forum https://forum.yunohost.org/search?q=migration%20buster
This thread is getting long and from here the issue is not related to Hubzilla.
You will first need to migrate to Buster then try to upgrade the Hubzilla.


Anyways, can you login from ssh?

**Comment by rocky-III** [comment]
not even try to migrat to buster but  just try to update the system ... 

login does not work as root with "shell in a Box" rihgt now
with ssh form my linux Pc it does work YES - thanks for the hint...

**Comment by rocky-III** [comment]
Fianaly i could restor the HZ installation 
THANK @anmol26s
