### ISSUE TITLE
Empty Stream after 5.02 upgrade

### ISSUE THREAD

**Issue by takemusu1160** [YunoHost-Apps/hubzilla_ynh#52]
Just tried 5.01 ==> 5.02 upgrade.

My stream was emptied. Contacts were OK.
Rollback-ed to 5.01. All, OK then.

**Comment by anmol26s** [comment]
You mean you lost all your stream? Or public stream? Or both?

**Comment by takemusu1160** [comment]
Hey, thanks for contacting me.
I just retried 10 minutes, ago, but this time the upgrade went from 5.0.1 to 5.0.3, and there is no problem anymore !
So it seems to be fixed in 5.0.3, or I had a problem which didn't occur this time...

Whatever, thanks for your support.
