### ISSUE TITLE
Preinstalled apps and préconfigured theme for "non geek" new user

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/hubzilla_ynh#66]
Hello, is there any possibility to have preinstalled apps ans also a pre-personnalised theme for new "non geek" user ?
I have a self host hubzilla instance installed on yunohost

**Comment by anmol26s** [comment]
You mean you want to install new theme?

**Comment by tutle** [comment]
No, but just a pre-personnalised theme and some app pre-installed

**Comment by anmol26s** [comment]
For apps you can choose them from add-ons by logging as admin. For custom theme you have options inside site again in admin. You can change lot of things from there. 
Do you need a theme specially build for according to you?
