### ISSUE TITLE
Custom Theme Settings Menu Blank

### ISSUE THREAD

**Issue by xavavu** [YunoHost-Apps/hubzilla_ynh#67]
Installed Hubzilla on 2 different YunoHost servers. On each one, the Custom Theme Settings menu at [URL]/settings/display appears to expand when selected, but is empty. Expect to see options to modify theme here.

**Comment by anmol26s** [comment]
Can you show the screenshot? I assume this is  Hubzilla's issue rather than a packaging problem.

**Comment by xavavu** [comment]
![customtheme](https://user-images.githubusercontent.com/80236500/110415617-06337100-8047-11eb-8413-3fa3ebd07b4d.png)

**Comment by anmol26s** [comment]
Are these instances fresh install?

**Comment by xavavu** [comment]
Yes. The screenshot is from a hub that was installed via YunoHost just this past week.

**Comment by anmol26s** [comment]
Can you update and see if its fixed? 
Or maybe a new instance would give us whats happening here.

**Comment by xavavu** [comment]
Same result on a newly installed hub and on the original hub that was just updated. Still nothing appears under "Custom Theme Settings."

**Comment by xavavu** [comment]
Follow-up:

I found that on a newly installed hub, the "theme" needs to be activated/selected first (even though only one theme is available at install).

From [base.url]/admin/themes one must mark the checkbox next to "Redbasic" then the Custom Theme Settings menu options become available.

I wonder whether Redbasic should come selected (box marked) by default on a new install.
