### ISSUE TITLE
No Login to Hubzilla

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/hubzilla_ynh#80]
### Describe the bug

log-in to hubzilla doesn't do anything. The log-in page only reloads without an error message
I've installed hubzilla 6.0~ynh1 and things went fine. No errors in the YH log

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.7 (stable) -  mysql
- I have access to my server: Webadmin+SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch:  6.0~ynh1

### Steps to reproduce

I'm launching the Hubzilla from a YH tile and the Hubzilla login page loads. 
I enter the users credentials and click the log-in button.
The page simply reloads without an error message and with empty log-in form. 
Log-in is not possible. I've tested 2 different users on 2 different Yunohost installations. I've also tried the domain/admin URL.

### Expected behaviour

Log-in should be possible or Hubzilla should show an error message if login is not possible. 
It didn't say that the password is wrong

trying wrong username or wrong password doesn't return a error messages. Same behaviour as above.
Remote authentication with Mastodon does also not work. There is some generic error message from Mastodon that something didn't work, but doesn't say what it is. 

just as a side note, with Hubzilla 5.6 I ran into issue #73
additionally, I have the same problem (no login possible) with friendica on Yunohost

### Logs

![Auswahl_002](https://user-images.githubusercontent.com/7679654/129460931-556da638-70d8-4cf6-a51a-a0bcb9978615.png)

Thanks for your support

**Comment by sthaydn** [comment]
Try to REGISTER the first user with the emailaddress you have chosen while installing from the yunohost GUI. This one should be the administrator then. Same for Friendica.
