### ISSUE TITLE
App is broken

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/hubzilla_ynh#9]
Hello

Your app failed to install.
I've an errors 500, Internal Server Error after installation.

See the log for more information:
https://jenkins-ci-arm.noho.st/jenkins/logs/github.com_anaqreon_hubzilla-yunohost_complete.log

So, if your app is not corrected before thursday, january 12th, it will be decreased at Notworking status.

**Comment by anaqreon** [comment]
I almost have an updated Hubzilla app working on the latest YunoHost. I'll update this issue when I commit the update.

**Comment by anaqreon** [comment]
I have tested the latest commit (https://github.com/YunoHost-Apps/hubzilla-yunohost/commit/9f9d78396eb7e0f637c076429380c0423b1a6b3a) with a fresh installation of the latest YunoHost.

**Comment by maniackcrudelis** [comment]
I'm performing a test on your app, I tell you the results as soon as possible.

But, if possible, is good to avoid to include the whole source of the app in your package. Just now, you broke my firefox with your last commit, it's really too huge ! It frozen my firefox during at least  5 minutes.

PS: You must add a [check_process](https://github.com/YunoHost/package_check#syntax-check_process-file) file to execute the tests with package check. If not, the continuuous integration fails on your app.

**Comment by maniackcrudelis** [comment]
Ok, the tests are good, at least for the installation and the suppression.
However, the upgrade fail on nginx restart.

But, for working, the install script needs an `apt-get update` just before the `install`.
At line 35.

For me, you can change the status of your app :)

**Comment by anaqreon** [comment]
I just added some updates, including a check_process file, but I am not sure how to run the tests. As for including the large number of source files: there is some processing and integration of two Hubzilla repos that we do for this package. It would be more difficult to do this at installation time, or at least I'm not sure how to do it then.

**Comment by maniackcrudelis** [comment]
To run tests, I use Package check.
You can find a readme in english [here](https://github.com/YunoHost/package_check/blob/master/README.md#package-checker-for-yunohost-1).
I'm running a test now.

For your problem with included sources, can you explain me how you do that?
If you fill your source dir with shell's commands, we should can do that in your script also.
I can help you if you need.

---

Warning, you have a small error in your upgrade script. I don't know why, but you've a fail on nginx reload. But your app still work.
All others work fine, except backup/restore of course.

**Comment by anmol26s** [comment]
The upgrade nginx fail was a log time pending  bug, which has been resolved now. You can test it and close the issue.
